language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./bin/test

script: ./bin/test

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build